In [1]:
import caffe
import numpy as np
# fcn8 (initial weights for TRAIN)
net = caffe.Net('voc-fcn8s-atonce/train.prototxt', 
                          'voc-fcn8s-atonce/vgg16fc.caffemodel',
                          caffe.TRAIN)

In [2]:
net.blobs.keys()

odict_keys(['data', 'label', 'data_data_0_split_0', 'data_data_0_split_1', 'conv1_1', 'conv1_2', 'pool1', 'conv2_1', 'conv2_2', 'pool2', 'conv3_1', 'conv3_2', 'conv3_3', 'pool3', 'pool3_pool3_0_split_0', 'pool3_pool3_0_split_1', 'conv4_1', 'conv4_2', 'conv4_3', 'pool4', 'pool4_pool4_0_split_0', 'pool4_pool4_0_split_1', 'conv5_1', 'conv5_2', 'conv5_3', 'pool5', 'fc6-conv', 'fc7-conv', 'score_fr', 'upscore2', 'upscore2_upscore2_0_split_0', 'upscore2_upscore2_0_split_1', 'scale_pool4', 'score_pool4', 'score_pool4c', 'fuse_pool4', 'upscore_pool4', 'upscore_pool4_upscore_pool4_0_split_0', 'upscore_pool4_upscore_pool4_0_split_1', 'scale_pool3', 'score_pool3', 'score_pool3c', 'fuse_pool3', 'upscore8', 'score', 'loss'])

In [3]:
# activations
net.blobs['conv2_1'].data

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        ..., 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0., 

In [4]:
# deltas
np.where(net.blobs['conv2_1'].diff!=0)

(array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64))

In [5]:
net.params.keys()

odict_keys(['conv1_1', 'conv1_2', 'conv2_1', 'conv2_2', 'conv3_1', 'conv3_2', 'conv3_3', 'conv4_1', 'conv4_2', 'conv4_3', 'conv5_1', 'conv5_2', 'conv5_3', 'fc6-conv', 'fc7-conv', 'score_fr', 'upscore2', 'scale_pool4', 'score_pool4', 'upscore_pool4', 'scale_pool3', 'score_pool3', 'upscore8'])

In [6]:
# weights
net.params['conv1_2'][0].data

array([[[[  1.66219279e-01,   2.12007999e-01,  -5.91698708e-03],
         [  1.99202523e-01,  -2.59410664e-02,  -9.84916389e-02],
         [ -1.11585744e-02,  -1.02114283e-01,   2.73401570e-02]],

        [[  9.46945231e-03,  -2.62175221e-03,  -3.93767562e-03],
         [ -1.38656620e-03,  -4.78290301e-03,   4.70533501e-03],
         [ -6.14583818e-03,   2.65349774e-03,   9.48381796e-03]],

        [[  6.32681847e-02,   2.27197763e-02,  -3.07008922e-02],
         [  2.14257818e-02,  -3.81173752e-02,  -2.28894763e-02],
         [ -1.00106997e-02,  -1.50703192e-02,   3.73495184e-02]],

        ..., 
        [[  3.47490981e-03,  -2.70304317e-03,   5.83332591e-03],
         [ -1.47800148e-02,  -1.79932006e-02,   2.93275771e-05],
         [ -1.68860350e-02,  -5.43789240e-03,  -2.60413792e-02]],

        [[  5.97234145e-02,  -3.20506282e-02,  -7.80934095e-02],
         [ -1.39283072e-02,  -8.91536921e-02,  -4.56118677e-03],
         [ -1.34146223e-02,  -2.21891310e-02,   2.67488584e-02]],

 

In [7]:
# biases
net.params['conv1_2'][1].data

array([-0.30912212,  0.36397225,  0.13737613,  0.07717966,  0.90521842,
        0.08885256,  0.10789118, -0.23106739, -0.63180971,  0.18161367,
       -0.33391494,  0.1961724 ,  0.43838617,  0.1938708 ,  0.10894354,
        0.10315038, -1.02715135,  0.05252688,  0.13118458,  0.22851577,
       -0.71377224,  0.21541549, -0.69819617,  0.04061132,  0.13955347,
        0.28767544,  0.35358745,  0.39372951,  0.43452853, -0.48259264,
        0.02631121,  0.09220165,  0.05196398,  0.55070502,  0.32368094,
        0.07263482, -0.17745508,  0.37619719,  0.39344102,  0.17673127,
       -0.15784228,  0.26051855,  0.08342359,  0.08603705, -0.09131282,
        0.22932515,  0.29983151,  0.13511261, -0.38358289,  0.10912544,
       -0.53432876,  0.4741787 , -0.0740848 ,  0.30046257,  0.12590808,
        0.16480374,  0.24039429,  0.23401979, -0.19334187,  0.01663565,
        0.27144948,  0.03385786,  0.06076292, -0.5825159 ], dtype=float32)